### ISSUE TITLE
App not showing up in Prometheus target

### ISSUE THREAD

**Issue by Akhilesh-Anb** [camilb/prometheus-kubernetes#36]
Hi,

Hope you are well! This repository helped me a lot to configure Prometheus and Grafana.
I have deployed a sample web application.
I need your help to get the Application metrics in targets page of prometheus. How can i achieve this.

Appreciate your help.

Thanks,
Akhilesh Appana

**Comment by Akhilesh-Anb** [comment]
Here is the yml file of the application:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app 
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    k8s-app: example-app
spec:
  selector:
    k8s-app: example-app
  ports:
  - name: web
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    k8s-app: example-app
spec:
  selector:
    matchLabels:
      k8s-app: example-app
  endpoints:
  - port: web
    interval: 10s

```

After deploying the application, i'm not able to see this in targets page of UI.
could you please help me on this.

**Comment by camilb** [comment]
Hi @Akhilesh-Anb please try this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: example-app
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    k8s-app: example-app
spec:
  selector:
    k8s-app: example-app
  ports:
  - name: web
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    k8s-app: example-app
spec:
  selector:
    matchLabels:
      k8s-app: example-app
  endpoints:
  - port: web
    interval: 10s
```
The problem was that you had a different label on pods than the service selector. 
Tested and works fine.

<img width="1259" alt="screen shot 2017-11-30 at 00 30 03" src="https://user-images.githubusercontent.com/2655869/33404799-f4d2014a-d565-11e7-93fc-90ff21e55e84.png">
