### ISSUE TITLE
Need to add Rabbitmq exporter to Prometheus configuration to scrape the data

### ISSUE THREAD

**Issue by abhijt-zanak** [camilb/prometheus-kubernetes#39]
I am creating custom dashboard wherein Prometheus will poll the data from rabbitmq exporter, please let me know where I can modify the Rabbitmq exporter any template to include the Rabbitmq exporter in scrape_configs.

**Comment by abhijt-zanak** [comment]
attaching rabbitmq deployment and service:
rabbitmq deployment
```
`
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: rezoomex-rabbitmq-deployment
 labels:
  app: queue
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: rabbitmq
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3.6.11-management-alpine
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
      ports:
        - name: rabbitmq
          containerPort: 5672
          protocol: TCP
        - name: rabbitmq1
          containerPort: 15672
          protocol: TCP
    - name: rabbitmq-exporter  
      image: kbudde/rabbitmq-exporter
      ports:
        - name: exporter 
          containerPort: 9090
      env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password
             
    # mount efs drive        
      volumeMounts:
       - mountPath: /var/lib/rabbitmq
         name: rezoomex-volume
    # Node selector      
   nodeSelector:
    services: other-services       
   volumes:
    - name: rezoomex-volume
      nfs:
        server: fs-8f298826.efs.us-west-2.amazonaws.com
        path: /

`
```
```
rabbitmq service
`apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"  
spec:
  type: LoadBalancer
  ports:
  - name: rabbitmq
    port: 5672
    #targetPort: 15672
    protocol: TCP
  - name: rabbitmq1
    port: 15672
    protocol: TCP
  - name: exporter
    port: 9090
    targetPort: exporter
    protocol: TCP
  selector:
    app: rabbitmq`
```

**Comment by camilb** [comment]
Hi @abhijt-zanak Please create this servicemonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    app: rabbitmq-service
spec:
  selector:
    matchLabels:
      app: rabbitmq-service
  endpoints:
  - port: exporter
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
```

**Comment by camilb** [comment]
For me works fine:

![screen shot 2017-12-05 at 18 28 59](https://user-images.githubusercontent.com/2655869/33621343-af901480-d9ea-11e7-94b1-cdd231bada77.png)

**Comment by abhijt-zanak** [comment]
Thanks for the reply.
I have added service monitor, however not able to see rabbitmq endpoint in Prometheus targets, in order to take effect Do I need do any other changes at Prometheus end? or do I need to do any more changes?

**Comment by camilb** [comment]
The `servicemonitor` has to be in the `monitoring` namespace and you have to specify the namespace of rabbitmq in the `namespaceSelector`. Here is the full example that works fine for me:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    #targetPort: 15672
    protocol: TCP
  - name: rabbitmq1
    port: 15672
    protocol: TCP
  - name: exporter
    port: 9090
    targetPort: exporter
    protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: rezoomex-rabbitmq-deployment
 labels:
  app: queue
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: rabbitmq
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3.6.11-management-alpine
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
      ports:
        - name: rabbitmq
          containerPort: 5672
          protocol: TCP
        - name: rabbitmq1
          containerPort: 15672
          protocol: TCP
    - name: rabbitmq-exporter
      image: kbudde/rabbitmq-exporter
      ports:
        - name: exporter
          containerPort: 9090
      env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    app: rabbitmq-service
spec:
  selector:
    matchLabels:
      app: rabbitmq-service
  endpoints:
  - port: exporter
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
```

**Comment by camilb** [comment]
@abhijt-zanak After erasing and creating again using the above configuration, it stopped working for me also. I'll update the issue after I find the solution. It works fine with any other apps. I think I miss something.

**Comment by abhijt-zanak** [comment]
ok, thanks for updating me.

**Comment by camilb** [comment]
As weird as may sound (maybe there is documented somewhere) but after changing the labels, everything works fine. I have changed the `app: rabbitmq` to `k8s-app: rabbitmq`. Deleted and recreated several times and it works. Here is the exact yaml I'm testing:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    k8s-app: rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    #targetPort: 15672
    protocol: TCP
  - name: rabbitmq1
    port: 15672
    protocol: TCP
  - name: exporter
    port: 9090
    targetPort: exporter
    protocol: TCP
  selector:
    k8s-app: rabbitmq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: rezoomex-rabbitmq-deployment
 labels:
  app: queue
spec:
 replicas: 1
 template:
  metadata:
   labels:
    k8s-app: rabbitmq
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3.6.11-management-alpine
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password
      ports:
        - name: rabbitmq
          containerPort: 5672
          protocol: TCP
        - name: rabbitmq1
          containerPort: 15672
          protocol: TCP
    - name: rabbitmq-exporter
      image: kbudde/rabbitmq-exporter
      ports:
        - name: exporter
          containerPort: 9090
      env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: monitoring
  labels:
    k8s-app: rabbitmq
spec:
  selector:
    matchLabels:
      k8s-app: rabbitmq
  endpoints:
  - port: exporter
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
```
