### ISSUE TITLE
How to add exports manually ?

### ISSUE THREAD

**Issue by IgorGerasimov** [camilb/prometheus-kubernetes#44]
Hello - how i can create target to some exporter - for example to redis ?
In what file i should add configuration.
Thank you.

**Comment by camilb** [comment]
Hi, first you need to configure [redis-exporter](https://github.com/oliver006/redis_exporter) similar to [node-exporter](https://github.com/camilb/prometheus-kubernetes/tree/master/manifests/node-exporter)

Then you should create a ServiceMonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    k8s-app: redis-exporter
spec:
  selector:
    matchLabels:
      k8s-app: redis-exporter
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
```
