### ISSUE TITLE
Monitoring NGiNX ingress

### ISSUE THREAD

**Issue by BTFO** [camilb/prometheus-kubernetes#60]
Hello!

Great piece of software, made deploying prometheus much easier and less painful!
I've however been running into a slight issue, when trying to get prometheus to recognize a nginx ingress that has been deployed using helm, it won't show up in the `/targets` list, other services can be monitored just fine, but NGiNX is the only one being stubborn.

Is this a configuration issue? If so, what could be done to get prometheus to recognize the NGiNX ServiceMonitor?

Thanks 👍 

<details>
 <summary>Deployment (click to expand)</summary>

```json
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "default-nginx-ingress-controller",
    "namespace": "ingress",
    "selfLink": "/apis/extensions/v1beta1/namespaces/ingress/deployments/default-nginx-ingress-controller",
    "uid": "a98f2411-fee1-11e7-b7ed-42010a840009",
    "resourceVersion": "159937",
    "generation": 5,
    "creationTimestamp": "2018-01-21T19:31:22Z",
    "labels": {
      "app": "nginx-ingress",
      "chart": "nginx-ingress-0.8.26",
      "component": "controller",
      "heritage": "Tiller",
      "release": "default-nginx-ingress"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "nginx-ingress",
        "component": "controller",
        "release": "default-nginx-ingress"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "nginx-ingress",
          "component": "controller",
          "release": "default-nginx-ingress"
        },
        "annotations": {
          "checksum/config": "ca0755a5e5dbce143322cdb78f9294bee8dffc1b806eee9b879211352ab1bd77"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "nginx-ingress-controller",
            "image": "k8s.gcr.io/nginx-ingress-controller:0.9.0-beta.15",
            "args": [
              "/nginx-ingress-controller",
              "--default-backend-service=ingress/default-nginx-ingress-default-backend",
              "--election-id=ingress-controller-leader",
              "--ingress-class=nginx",
              "--configmap=ingress/default-nginx-ingress-controller"
            ],
            "ports": [
              {
                "name": "http",
                "containerPort": 80,
                "protocol": "TCP"
              },
              {
                "name": "https",
                "containerPort": 443,
                "protocol": "TCP"
              },
              {
                "name": "stats",
                "containerPort": 18080,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.name"
                  }
                }
              },
              {
                "name": "POD_NAMESPACE",
                "valueFrom": {
                  "fieldRef": {
                    "apiVersion": "v1",
                    "fieldPath": "metadata.namespace"
                  }
                }
              }
            ],
            "resources": {},
            "livenessProbe": {
              "httpGet": {
                "path": "/healthz",
                "port": 10254,
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 10,
              "timeoutSeconds": 1,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "readinessProbe": {
              "httpGet": {
                "path": "/healthz",
                "port": 10254,
                "scheme": "HTTP"
              },
              "timeoutSeconds": 1,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          },
          {
            "name": "nginx-ingress-stats-exporter",
            "image": "sophos/nginx-vts-exporter:v0.6",
            "ports": [
              {
                "name": "metrics",
                "containerPort": 9913,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "METRICS_ADDR",
                "value": ":9913"
              },
              {
                "name": "METRICS_ENDPOINT",
                "value": "/metrics"
              },
              {
                "name": "METRICS_NS",
                "value": "nginx"
              },
              {
                "name": "NGINX_STATUS",
                "value": "http://localhost:18080/nginx_status/format/json"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 60,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "default-nginx-ingress",
        "serviceAccount": "default-nginx-ingress",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 10
  },
  "status": {
    "observedGeneration": 5,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-01-21T19:31:22Z",
        "lastTransitionTime": "2018-01-21T19:31:22Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
```
</details>

<details>
 <summary>ServiceMonitor (click to expand)</summary>

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-monitor
  namespace: monitoring
  labels:
    k8s-app: nginx-ingress
spec:
  selector:
    matchLabels:
      k8s-app: nginx-ingress
  endpoints:
  - port: exporter
    interval: 10s
  namespaceSelector:
    matchNames:
    - ingress
```
</details>

**Comment by camilb** [comment]
Hi @BTFO, can you please check the prometheus logs and make sure you don't have any error similar to this:

```
level=error ts=2018-01-22T15:42:34.436552996Z caller=main.go:211 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:178: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list services in the namespace \"nginx-ingress\""
```
I think that by default RBAC isn't configured to allow listing services on other namespaces than `default`, `kube-system` and `monitoring` 

I'm using a different method to monitor the nginx-ingress by setting `enable-vts-status: "true"` in `ingress-nginx` configmap Ref: [here](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/customization/custom-vts-metrics-prometheus) and I can share it if the RBAC isn't the issue.

**Comment by BTFO** [comment]
> Hi @BTFO, can you please check the prometheus logs and make sure you don't have any error similar to this:

I've checked the logs of the `prometheus` pod and was unable to find anything relevant

> I'm using a different method to monitor the nginx-ingress by setting <...>

Please do share!

**Comment by camilb** [comment]
@BTFO Here it is:
```yaml
apiVersion: v1
data:
  enable-vts-status: "true"
  use-proxy-protocol: "true"
kind: ConfigMap
metadata:
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  name: ingress-nginx
  namespace: nginx-ingress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
    k8s-app: nginx-ingress
  name: ingress-nginx
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
      k8s-addon: ingress-nginx.addons.k8s.io
      k8s-app: nginx-ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ingress-nginx
        k8s-addon: ingress-nginx.addons.k8s.io
        k8s-app: nginx-ingress
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/nginx-default-backend
        - --configmap=$(POD_NAMESPACE)/ingress-nginx
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ingress-nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 10254
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: metrics
  namespaceSelector:
    matchNames:
    - nginx-ingress
  selector:
    matchLabels:
      k8s-app: nginx-ingress
```
