### ISSUE TITLE
Using the same prometheus setup for scraping other services' metrics

### ISSUE THREAD

**Issue by MansoorMajeed** [camilb/prometheus-kubernetes#70]
How do I use the same prometheus setup to get metrics from another service, say an Nginx VM which is outside of kubernetes. ? How do I add a new scrape rule?

**Comment by camilb** [comment]
Never tested before, but it may work:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  externalName: 1.2.3.4 #vm_ip_address
  type: ExternalName
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx
  labels:
    k8s-app: nginx
subsets:
- addresses:
  - ip: 1.2.3.4 # vm_ip_address
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: monitoring
  labels:
    k8s-app: nginx
spec:
  selector:
    matchLabels:
      k8s-app: nginx
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
```

**Comment by MansoorMajeed** [comment]
It worked. There is a tiny change


```
  type: ExternalName
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
```

should be 

```
  type: ExternalName
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
```


Thank you so much :)
