### ISSUE TITLE
I'm not seeing my services show up when I scrape

### ISSUE THREAD

**Issue by posix4e** [camilb/prometheus-kubernetes#85]
Do you have something misconfigured. I was under the impression that if I launch my services with
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
  creationTimestamp: null
```
Operator would pick them up on <svc.namespace....>:5000/metrics What gives? Why don't I see them in the service discovery screen?
