### ISSUE TITLE
node-exporter Kubernetes node labels missing

### ISSUE THREAD

**Issue by paalkr** [camilb/prometheus-kubernetes#88]
Hi

I encounter the same issue as described here
https://github.com/prometheus/prometheus/issues/3294
when deploying Prometheus

Earlier (before the Prometheus operator implementation) metrics like
`container_memory_working_set_bytes{id='/'}`
provided all the node labels 
![image](https://user-images.githubusercontent.com/9726307/41251068-2324717c-6db9-11e8-8a6d-25bc04313aac.png)

But unfortunately now must of the useful labels ar not there anymore. Is it possible to configure the node-exporter to add node labels?
![image](https://user-images.githubusercontent.com/9726307/41251222-915f3730-6db9-11e8-8c1e-00033c2508ae.png)

**Comment by camilb** [comment]
Hi @paalkr, sorry for the late reply. I did try to fix it but unfortunately wasn't able to do it. Tested also with `TargetLables` and still not working. I think I'll need more time to understand exactly how this work. 

Here is the example I tried:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  labels:
    k8s-app: kubelet
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
  selector:
    matchLabels:
      k8s-app: kubelet
  targetLabels:
    - app
    - prometheus
    - beta.kubernetes.io/instance-type
    - kops.k8s.io/instancegroup
    - failure-domain.beta.kubernetes.io/zone
    - name
    - address
  namespaceSelector:
    matchNames:
    - kube-system
```

**Comment by paalkr** [comment]
Hi, thanks  for looking into this, I appreciate your effort and help.

**Comment by paalkr** [comment]
May this be of any help?
https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/servicemonitor.crd.yaml

**Comment by paalkr** [comment]
Hi, id did notice a big commit yesterday. Did you have any success to get the labels applied?

**Comment by camilb** [comment]
No luck yet

**Comment by paalkr** [comment]
Ah, I see. Thanks for the feedback. anything I can do to help?

**Comment by paalkr** [comment]
Some more interesting information
https://github.com/coreos/prometheus-operator/issues/1166
https://github.com/coreos/prometheus-operator/issues/1548#issuecomment-402045553

**Comment by paalkr** [comment]
I managed to sort out this issue. There are several things worth mentioning.
The Prometheus Operator ServiceMonitor object/kind/crd does not provide access to the kubernetes_sd_config role=node
```
  kubernetes_sd_configs:
  - api_server: null
    role: node
```
And therefor non of the `__meta_kubernetes_node_*` labels are available. This can be worked around using `additionalScrapeConfigs` in the PrometheusSpec (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).

Trying to use `targetLabels` in the service monitor will fail, becasue they will translate into
`__meta_kubernetes_service_label_<labelname>` as the role of targets created by the automated processes in the operator always are service.
```
  kubernetes_sd_configs:
  - api_server: null
    role: service
```

So I ended up removing the kubelet ServiceMonitor (prometheus-k8s-service-monitor-kubelet.yaml), and replacing this with a custom scarping config. To get this to work you have to do several things.

1. Alter the rbac config to allow node access a the cluster scope
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics  
  - nodes  
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"] 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics
  - nodes  
  - endpoints
  - pods
  - services
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

2. Create a yaml file with your custom scraping configs
kubelet.yaml
```
- job_name: 'kubernetes-nodes'
  scheme: https
  metrics_path: /metrics
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__meta_kubernetes_node_address_InternalIP]      
    target_label: __address__
    regex: (.+)
    replacement: ${1}:10250

- job_name: 'kubernetes-cadvisor'
  scheme: https
  metrics_path: /metrics/cadvisor
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__meta_kubernetes_node_address_InternalIP]      
    target_label: __address__
    regex: (.+)
    replacement: ${1}:10250  
```

3. Create a secret with content from the custom scraping config yaml
`kubectl create secret generic additional-scrape-configs --from-file=kubelet.yaml=.\kubelet.yaml`

4. Modify the Prometheus config to include the customs scraping configs
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  externalUrl: xxx
  replicas: 2
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: prometheus-rulefiles
  serviceAccountName: prometheus-k8s
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: kubelet.yaml
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.2.1
```

All node labels are then propagated to metrics like `container_memory_working_set_bytes`, `machine_memory_bytes` etc.

![image](https://user-images.githubusercontent.com/9726307/45410045-171aeb80-b671-11e8-8a42-640f7eb0db3c.png)

![image](https://user-images.githubusercontent.com/9726307/45410110-429dd600-b671-11e8-9545-2ab849f2b6b5.png)

**Comment by camilb** [comment]
Hi @paalkr, thanks for this fix. I'll try to integrate it in the next update.

**Comment by estahn** [comment]
@camilb I'm facing the same issue with the `node-exporter`.

**Comment by puneetmathur-87** [comment]
Do we have any work around for now to get the node name label in the metrics without additionalScrape config ?

**Comment by Blaumer** [comment]
> with respect to node-exporter o we have any work around for now to get the node name label in the metrics without additionalScrape config ?

bumppppp there has to be a better way to do this

**Comment by puneetmathur-87** [comment]
please help me understand that. I am really looking for prometheus operator use name labels on nodes.
PUNEET 

    On Wednesday, 1 July 2020, 10:57:42 PM IST, Blaumer <notifications@github.com> wrote:  
 
 



with respect to node-exporter o we have any work around for now to get the node name label in the metrics without additionalScrape config ?


bumppppp there has to be a better way to do this

**Comment by camilb** [comment]
I'll take a look on it later today

**Comment by puneetmathur-87** [comment]
thanks a lot.. just let me know when you check.. I will try that immediately.
PUNEET 

    On Thursday, 2 July 2020, 07:49:56 AM IST, Camil Blanaru <notifications@github.com> wrote:  
 
 


I'll take a look on it later today

**Comment by izavadynskyi** [comment]
Hi guys.
I have faced with the same issue.
Do we have any updates regarding the solution?

**Comment by izavadynskyi** [comment]
I have solved it by used group_left in query.
sum by(label_node_type, node) (kube_node_status_allocatable_cpu_cores * on(node) group_left(label_node_type) kube_node_labels)

**Comment by sainih09** [comment]
Hi guys, probably this is a more cleaner way to do this (on the serviceMonitor object)

```yaml
prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: node
```
These values are for [kube-prometheus-stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack). Check service discovery on prometheus for more labels. most of the useful ones are available.
