### ISSUE TITLE
How to get jmx metrics in prometheus-kubernetes project?

### ISSUE THREAD

**Issue by andrvin** [camilb/prometheus-kubernetes#91]
Hi guys! Thank you for your job!
Everything is good, but I just don't know how to get metrics from prometheus jmx exporter agent.
The agent is installed in app container and listen on 9090 port:

`    spec:
      containers:
      - image: registry/image:version
        imagePullPolicy: Always
        name: app-name
        env:
        - name: JAVA_CUSTOM_OPTS
          value: "-Xms256m -Xmx512m -javaagent:./jmx_prometheus_javaagent.jar=9090:jmx/prom-jmx-agent-config.yml"
        ports:
        - name: app
          containerPort: 8080
        - name: monitoring
          containerPort: 9090 `

How I can add this new target into prometheus configuration? Usually I just have to edit prometheus.yml config file, but I don't understand how to add it into your configuration.

**Comment by camilb** [comment]
Hi @andrvin this should work, you have to replace the selector label and the namespace.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jmx
  namespace: monitoring
  labels:
    k8s-app: jmx
spec:
  selector:
    matchLabels:
      your_label_key: your_label_value
  endpoints:
  - port: monitoring
    interval: 10s
  namespaceSelector:
    matchNames:
    - your_app_namespace
```
Save it to a file and `kubectl create -f file.yaml`
